---
elixir:
  redirectUri: "Elixir AAI Redirect URI"
  id: "Elixir AAI client id"
  secret: "Elixir AAI client secret"
bindAddress: "127.0.0.1"
port: 31111
logLevel: "DEBUG"
certFile: "elixir.ca.crt"
keyFile: "elixir.ca.key"
caCerts: "root.ca.crt"