---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  selector:
    matchLabels:
      run: auth-server
  replicas: 1
  template:
    metadata:
      labels:
        run: auth-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: auth-server
        image: "nbisweden/elixir-auth-srv:stable" 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    run: auth-server
spec:
  type: ClusterIP
  ports:
  - port: 8080 
    targetPort: 8080
  selector:
    run: auth-server
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: login.ega.nbis.se
    http:
      paths:
      - backend:
          serviceName: auth-server
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - login.ega.nbis.se
    secretName: login-ingress-cert
