version: '3.7'
services:
  oidc:
    build:
      context: ./oidc
      dockerfile: Dockerfile
    image: mock-oidc-user-server
    environment:
      - PORT=9090
      - CLIENT_ID=XC56EL11xx
      - CLIENT_SECRET=wHPVQaYXmdDHg
      - CLIENT_REDIRECT_URI=http://backend:31111/elixir/login
    ports:
      - 9090:9090
  cega:
    image: egarchive/lega-base:release.v0.2.0
    volumes:
      - ./cega-users:/cega
    command: ["python", "/cega/cega-mock.py", "0.0.0.0", "8443", "/cega/users.json"]
    environment:
      - LEGA_INSTANCES=dummy
      - CEGA_USERS_PASSWORD=dummy
      - CEGA_USERS_USER=dummy
    ports:
      - 8443:8443
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../keys:/keys
      - ../:/sda-auth
    image: sda-auth
    ports:
      - 31111:31111
