version: '3.7'
services:
  oidc:
    container_name: oidc
    build:
      context: ./oidc
      dockerfile: Dockerfile
    image: mock-oidc-user-server
    environment:
      - PORT=9090
      - HOST=oidc
      - CLIENT_ID=XC56EL11xx
      - CLIENT_SECRET=wHPVQaYXmdDHg
      - CLIENT_REDIRECT_URI=http://localhost:31111/elixir/login
      - AUTH_ROUTE=/auth
      - INTROSPECTION_ROUTE=/token/introspection
      - JWKS_ROUTE=/jwks
      - REVOCATION_ROUTE=/token/revocation
      - TOKEN_ROUTE=/token
      - USERINFO_ROUTE=/userinfo
    ports:
      - 9090:9090
  cega:
    container_name: cega
    image: egarchive/lega-base:release.v0.2.0
    volumes:
      - ./cega-users:/cega
    command: ["python", "/cega/cega-mock.py", "0.0.0.0", "8443", "/cega/users.json"]
    environment:
      - LEGA_INSTANCES=dummy
      - CEGA_USERS_PASSWORD=dummy
      - CEGA_USERS_USER=dummy
    ports:
      - 8443:8443
  auth:
    container_name: auth
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=DEBUG
      - CONF_FILE_PATH=/sda-auth/settings-sample.yaml
    volumes:
      - ../keys:/keys
      - ../:/sda-auth
    image: sda-auth
    ports:
      - 31111:31111
